MechaCarChart <- read.csv(file='MechaCar_mpg.csv')
class(MechaCarChart)
install.packages("dplyr")
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, MechaCarChart)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, MechaCarChart))
Suspension_Coil_Chart <- read.csv(file='Suspension_Coil.csv')
total_summary <- Suspension_Coil_Chart %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups='keep')
lot_summary <- Suspension_Coil_Chart %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups='keep')